version: "3.3"


services:


#  nginx:
#    image: alimizan/react-chat-nginx:latest
#    ports:
#      - 80:80
#    container_name: nginx

  frontend:
#    image: alimizan/frontend-chat:latest  
    build: ./Frontend/app
    links:
      - backend
    ports:
      - 3000:3000
    container_name: frontend

  backend:
    image: alimizan/backend-chat:latest
    ports:
      - 8080:8080
    container_name: backend

