version: "3.3"


services:


  frontend:
    image: alimizan/frontend-chat:latest  
    build: ./Frontend/app
    links:
      - backend
    ports:
      - 3000:3000
    container_name: frontend

  backend:
    image: alimizan/backend-chat:latest
    build: ./Backend
    ports:
      - 8080:8080
    container_name: backend

