version: "3.3"


services:


  nginx:
    image: alimizan/todo-nginx:latest
    ports:
      - 80:80
    container_name: nginx

  frontend:
    image: alimizan/react-chat-frontend:latest
    ports:
      - 3000:3000
    container_name: frontend

  backend:
    image: alimizan/react-chat-backend:latest
    ports:
      - 8080:8080
    container_name: backend

